### ISSUE TITLE
ValueError: '__init__' in __slots__ conflicts with class variable

### ISSUE THREAD

**Issue by ZoomQuiet** [Dobiasd/img2xls#4]
local env.

$ python
Python 3.4.2 (default, Feb 11 2015, 19:13:53)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

$ pip list
Pillow (2.8.1)
pip (1.5.6)
setuptools (2.1)
xlwt3 (0.1.2)

fixed img2xls.py
import xlwt
-->
import xlwt3

BUT:

$ python img2xls/img2xls.py libre Lenna.png
Traceback (most recent call last):
  File "img2xls/img2xls.py", line 5, in <module>
    import xlwt3
  File "/Users/zoomq/.pyenv/versions/342Chaos/lib/python3.4/site-packages/xlwt3/**init**.py", line 3, in <module>
    from .workbook import Workbook
  File "/Users/zoomq/.pyenv/versions/342Chaos/lib/python3.4/site-packages/xlwt3/workbook.py", line 5, in <module>
    from .worksheet import Worksheet
  File "/Users/zoomq/.pyenv/versions/342Chaos/lib/python3.4/site-packages/xlwt3/worksheet.py", line 7, in <module>
    from .row import Row
  File "/Users/zoomq/.pyenv/versions/342Chaos/lib/python3.4/site-packages/xlwt3/row.py", line 8, in <module>
    from . import formula
  File "/Users/zoomq/.pyenv/versions/342Chaos/lib/python3.4/site-packages/xlwt3/formula.py", line 6, in <module>
    class Formula(object):
ValueError: '**init**' in **slots** conflicts with class variable

**Comment by Dobiasd** [comment]
Thanks for reporting. Do you also get this error message if you reduce the script to this one single line?

```
import xlwt3
```

**Comment by wuzhaozhongguo** [comment]
I also have this error

**Comment by Dobiasd** [comment]
@wuzhaozhongguo Do you also get this error message if you reduce the script to this one single line?

```
import xlwt3
```
